In [268]:
import numpy as np 
import pandas as pd

In [269]:
data=np.arange(6,11)
data

array([ 6,  7,  8,  9, 10])

In [270]:
pd_series1=pd.Series(data=data)
pd_series1
print('2nd index : ')
pd_series1[1]

2nd index :

np.int64(7)

In [271]:
indx=np.array([chr(i) for i in range(ord('a'),ord('f'))])
indx

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [272]:
pd_series1.index=indx
pd_series1

a     6
b     7
c     8
d     9
e    10
dtype: int64

In [273]:
print('2nd index : ')
pd_series1['b']

2nd index :

np.int64(7)

In [274]:
pd_series2=pd.Series(data=data*2 ,index=indx) 
pd_series2

a    12
b    14
c    16
d    18
e    20
dtype: int64

In [275]:
dic={
    'a' : 'Tamzid', 
    'b' : 'Ronaldo', 
    'c' : 'Totty'
}
pd_series3=pd.Series(data=dic) 
pd_series3
print('2nd index : ') 
pd_series3['b']

2nd index :

'Ronaldo'

In [276]:
#2

In [277]:
data= np.random.rand(6,5) 
data

array([[0.69254254, 0.75281172, 0.08304189, 0.1173108 , 0.8274054 ],
       [0.94006413, 0.11053706, 0.61691456, 0.13267617, 0.91348035],
       [0.46864064, 0.24426244, 0.44897958, 0.65828172, 0.7991823 ],
       [0.34413509, 0.99529284, 0.4120035 , 0.48068604, 0.95062682],
       [0.20228826, 0.53568065, 0.27281439, 0.90144334, 0.90745097],
       [0.64461421, 0.56452722, 0.00262807, 0.40303004, 0.40272499]])

In [278]:
df=pd.DataFrame(data) 
df

          0         1         2         3         4
0  0.692543  0.752812  0.083042  0.117311  0.827405
1  0.940064  0.110537  0.616915  0.132676  0.913480
2  0.468641  0.244262  0.448980  0.658282  0.799182
3  0.344135  0.995293  0.412004  0.480686  0.950627
4  0.202288  0.535681  0.272814  0.901443  0.907451
5  0.644614  0.564527  0.002628  0.403030  0.402725

In [279]:
df.loc[:,[0,1,2]]

          0         1         2
0  0.692543  0.752812  0.083042
1  0.940064  0.110537  0.616915
2  0.468641  0.244262  0.448980
3  0.344135  0.995293  0.412004
4  0.202288  0.535681  0.272814
5  0.644614  0.564527  0.002628

In [280]:
df.loc[[0,1,2]]

          0         1         2         3         4
0  0.692543  0.752812  0.083042  0.117311  0.827405
1  0.940064  0.110537  0.616915  0.132676  0.913480
2  0.468641  0.244262  0.448980  0.658282  0.799182

In [281]:
df.loc[[1,2],[0,1,2]]

          0         1         2
1  0.940064  0.110537  0.616915
2  0.468641  0.244262  0.448980

In [282]:
df.loc[3,1]

np.float64(0.9952928376616355)

In [283]:
df[0]

0    0.692543
1    0.940064
2    0.468641
3    0.344135
4    0.202288
5    0.644614
Name: 0, dtype: float64

In [284]:
type(df[0]) #every column is a series

pandas.core.series.Series

In [285]:
df.loc[0,:]

0    0.692543
1    0.752812
2    0.083042
3    0.117311
4    0.827405
Name: 0, dtype: float64

In [286]:
type(df.iloc[0,:]) # every rows are series as well

pandas.core.series.Series

In [287]:
row=['r1','r2','r3','r4','r5','r5']
col=['c1','c2','c3','c4','c5']
df2=pd.DataFrame(data=data,index=row,columns=col) 
df2

          c1        c2        c3        c4        c5
r1  0.692543  0.752812  0.083042  0.117311  0.827405
r2  0.940064  0.110537  0.616915  0.132676  0.913480
r3  0.468641  0.244262  0.448980  0.658282  0.799182
r4  0.344135  0.995293  0.412004  0.480686  0.950627
r5  0.202288  0.535681  0.272814  0.901443  0.907451
r5  0.644614  0.564527  0.002628  0.403030  0.402725

In [288]:
df2.loc[:,['c2','c3','c4']]

          c2        c3        c4
r1  0.752812  0.083042  0.117311
r2  0.110537  0.616915  0.132676
r3  0.244262  0.448980  0.658282
r4  0.995293  0.412004  0.480686
r5  0.535681  0.272814  0.901443
r5  0.564527  0.002628  0.403030

In [289]:
df2.iloc[:,[1,2,3]]

          c2        c3        c4
r1  0.752812  0.083042  0.117311
r2  0.110537  0.616915  0.132676
r3  0.244262  0.448980  0.658282
r4  0.995293  0.412004  0.480686
r5  0.535681  0.272814  0.901443
r5  0.564527  0.002628  0.403030

In [290]:
df2['new']=np.random.rand(6) 
df2

          c1        c2        c3        c4        c5       new
r1  0.692543  0.752812  0.083042  0.117311  0.827405  0.948617
r2  0.940064  0.110537  0.616915  0.132676  0.913480  0.687500
r3  0.468641  0.244262  0.448980  0.658282  0.799182  0.687999
r4  0.344135  0.995293  0.412004  0.480686  0.950627  0.357460
r5  0.202288  0.535681  0.272814  0.901443  0.907451  0.275171
r5  0.644614  0.564527  0.002628  0.403030  0.402725  0.657010

In [291]:
df2.loc['r6',:]=np.random.rand(6) 
df2

          c1        c2        c3        c4        c5       new
r1  0.692543  0.752812  0.083042  0.117311  0.827405  0.948617
r2  0.940064  0.110537  0.616915  0.132676  0.913480  0.687500
r3  0.468641  0.244262  0.448980  0.658282  0.799182  0.687999
r4  0.344135  0.995293  0.412004  0.480686  0.950627  0.357460
r5  0.202288  0.535681  0.272814  0.901443  0.907451  0.275171
r5  0.644614  0.564527  0.002628  0.403030  0.402725  0.657010
r6  0.599947  0.627170  0.702551  0.417233  0.612589  0.169015

In [292]:
row=['r1','r2','r3']
col=['c1','c2']
data=np.random.rand(3,2)
df3=pd.DataFrame(data=data,index=row,columns=col) 
df3

          c1        c2
r1  0.055735  0.149922
r2  0.260342  0.527159
r3  0.541703  0.709165

In [293]:
dic={
    'r1' : [1,2,3,3,5], 
    'r2' : [9,8,7,6,5]
}
df4=pd.DataFrame(data=dic) 
df4

   r1  r2
0   1   9
1   2   8
2   3   7
3   3   6
4   5   5

In [294]:
#but its taking dic input as a column so we will transpose it 
df4=df4.T
df4

    0  1  2  3  4
r1  1  2  3  3  5
r2  9  8  7  6  5

In [295]:
#3

In [296]:
df4.drop(2,inplace= True ,axis=1)
df4

    0  1  3  4
r1  1  2  3  5
r2  9  8  6  5

In [297]:
df4.drop('r1',inplace=True ,axis=0)
df4

    0  1  3  4
r2  9  8  6  5

In [298]:
df=df.T
df

          0         1         2         3         4         5
0  0.692543  0.940064  0.468641  0.344135  0.202288  0.644614
1  0.752812  0.110537  0.244262  0.995293  0.535681  0.564527
2  0.083042  0.616915  0.448980  0.412004  0.272814  0.002628
3  0.117311  0.132676  0.658282  0.480686  0.901443  0.403030
4  0.827405  0.913480  0.799182  0.950627  0.907451  0.402725

In [299]:
df.drop([2,4],inplace=True,axis=1) 
df

          0         1         3         5
0  0.692543  0.940064  0.344135  0.644614
1  0.752812  0.110537  0.995293  0.564527
2  0.083042  0.616915  0.412004  0.002628
3  0.117311  0.132676  0.480686  0.403030
4  0.827405  0.913480  0.950627  0.402725

In [300]:
df2

          c1        c2        c3        c4        c5       new
r1  0.692543  0.752812  0.083042  0.117311  0.827405  0.948617
r2  0.940064  0.110537  0.616915  0.132676  0.913480  0.687500
r3  0.468641  0.244262  0.448980  0.658282  0.799182  0.687999
r4  0.344135  0.995293  0.412004  0.480686  0.950627  0.357460
r5  0.202288  0.535681  0.272814  0.901443  0.907451  0.275171
r5  0.644614  0.564527  0.002628  0.403030  0.402725  0.657010
r6  0.599947  0.627170  0.702551  0.417233  0.612589  0.169015

In [301]:
df2>0.5

       c1     c2     c3     c4     c5    new
r1   True   True  False  False   True   True
r2   True  False   True  False   True   True
r3  False  False  False   True   True   True
r4  False   True  False  False   True  False
r5  False   True  False   True   True  False
r5   True   True  False  False  False   True
r6   True   True   True  False   True  False

In [302]:
df2[df2>0.3]

          c1        c2        c3        c4        c5       new
r1  0.692543  0.752812       NaN       NaN  0.827405  0.948617
r2  0.940064       NaN  0.616915       NaN  0.913480  0.687500
r3  0.468641       NaN  0.448980  0.658282  0.799182  0.687999
r4  0.344135  0.995293  0.412004  0.480686  0.950627  0.357460
r5       NaN  0.535681       NaN  0.901443  0.907451       NaN
r5  0.644614  0.564527       NaN  0.403030  0.402725  0.657010
r6  0.599947  0.627170  0.702551  0.417233  0.612589       NaN

In [303]:
(df2['c1']>0.1) & (df2['c2']>0.1 ) & (df2['c3']>0.1 ) & (df2['c4']>0.1 ) & (df2['c5']>0.06 ) & (df2['new']>0.1 )

r1    False
r2     True
r3     True
r4     True
r5     True
r5    False
r6     True
dtype: bool

In [304]:
df2[(df2['c1']>0.1) & (df2['c2']>0.1 ) & (df2['c3']>0.1 ) & (df2['c4']>0.1 ) & (df2['c5']>0.06 ) & (df2['new']>0.1 )][['c2','c4']]

          c2        c4
r2  0.110537  0.132676
r3  0.244262  0.658282
r4  0.995293  0.480686
r5  0.535681  0.901443
r6  0.627170  0.417233

In [305]:
#4

In [313]:
level1=['groupA']*3 + ['groupB']*3
level2=['r1','r2','r3','r4','r5','r6'] 
col=['c1','c2','c3']
level1

['groupA', 'groupA', 'groupA', 'groupB', 'groupB', 'groupB']

In [314]:
index=list(zip(level1,level2))
index

[('groupA', 'r1'),
 ('groupA', 'r2'),
 ('groupA', 'r3'),
 ('groupB', 'r4'),
 ('groupB', 'r5'),
 ('groupB', 'r6')]

In [315]:
indx=pd.MultiIndex.from_tuples(tuples=index)

In [316]:
df=pd.DataFrame(
    data=np.random.rand(6,3), 
    columns=col, 
    index=indx
)
df

                 c1        c2        c3
groupA r1  0.215930  0.380022  0.060019
       r2  0.091130  0.532421  0.040832
       r3  0.994084  0.352010  0.140624
groupB r4  0.285925  0.583193  0.383710
       r5  0.497314  0.483754  0.229562
       r6  0.700674  0.151354  0.117912

In [317]:
df.index.names=['group','row'] 
df

                  c1        c2        c3
group  row
groupA r1   0.215930  0.380022  0.060019
       r2   0.091130  0.532421  0.040832
       r3   0.994084  0.352010  0.140624
groupB r4   0.285925  0.583193  0.383710
       r5   0.497314  0.483754  0.229562
       r6   0.700674  0.151354  0.117912

In [322]:
df.xs('groupA')

           c1        c2        c3
row
r1   0.215930  0.380022  0.060019
r2   0.091130  0.532421  0.040832
r3   0.994084  0.352010  0.140624

In [323]:
df.xs('r2', level='row')

             c1        c2        c3
group
groupA  0.09113  0.532421  0.040832

In [324]:
df.xs('groupA')
df.xs('r2', level='row')

             c1        c2        c3
group
groupA  0.09113  0.532421  0.040832

In [331]:
lv1=['gpA']*3+['gpB']*3 
lv2=['r1','r2','r3','r4','r5','r6']  
col=['c1','c2']
ind=list(zip(lv1,lv2)) 
indx=pd.MultiIndex.from_tuples(tuples=ind)
dff=pd.DataFrame(
    data=np.random.rand(6,2),
    columns=col, 
    index=indx
)
dff.index.names=['l1','l2'] 
# dff.xs('r1',level='l2'); 
dff

              c1        c2
l1  l2
gpA r1  0.931335  0.518852
    r2  0.702789  0.920504
    r3  0.579326  0.444000
gpB r4  0.838026  0.859934
    r5  0.386310  0.196097
    r6  0.570390  0.562833

In [332]:
#5

In [341]:
df=pd.DataFrame(
    data=np.random.rand(5,5)
)
df

          0         1         2         3         4
0  0.907335  0.833265  0.163038  0.323951  0.596097
1  0.116093  0.894986  0.043248  0.784609  0.329853
2  0.377452  0.656153  0.661153  0.943848  0.791364
3  0.578281  0.304689  0.571778  0.101722  0.259694
4  0.877735  0.579228  0.122576  0.634953  0.122458

In [347]:
df=df[df>0.2]
df

          0         1         2         3         4
0  0.907335  0.833265       NaN  0.323951  0.596097
1       NaN  0.894986       NaN  0.784609  0.329853
2  0.377452  0.656153  0.661153  0.943848  0.791364
3  0.578281  0.304689  0.571778       NaN  0.259694
4  0.877735  0.579228       NaN  0.634953       NaN

In [346]:
df.dropna()

          0         1         2         3         4
2  0.377452  0.656153  0.661153  0.943848  0.791364

In [349]:
df.dropna(axis=1)

          1
0  0.833265
1  0.894986
2  0.656153
3  0.304689
4  0.579228

In [350]:
df.dropna(axis=0, thresh=df.shape[1]-1)

          0         1         2         3         4
0  0.907335  0.833265       NaN  0.323951  0.596097
2  0.377452  0.656153  0.661153  0.943848  0.791364
3  0.578281  0.304689  0.571778       NaN  0.259694

In [351]:
df.fillna(value=0)
df

          0         1         2         3         4
0  0.907335  0.833265       NaN  0.323951  0.596097
1       NaN  0.894986       NaN  0.784609  0.329853
2  0.377452  0.656153  0.661153  0.943848  0.791364
3  0.578281  0.304689  0.571778       NaN  0.259694
4  0.877735  0.579228       NaN  0.634953       NaN

In [352]:
df.fillna({
    0 : df[0].median(), 
    1 : df[1].median(),
    2 : df[2].median(),
    3 : df[3].median(),
    4 : df[4].median(), 
    
},inplace=True)

In [353]:
df

          0         1         2         3         4
0  0.907335  0.833265  0.616466  0.323951  0.596097
1  0.728008  0.894986  0.616466  0.784609  0.329853
2  0.377452  0.656153  0.661153  0.943848  0.791364
3  0.578281  0.304689  0.571778  0.709781  0.259694
4  0.877735  0.579228  0.616466  0.634953  0.462975

In [375]:
#test

In [356]:
df2=pd.DataFrame(
    data=np.random.rand(5,5)
)
df2

          0         1         2         3         4
0  0.942650  0.382884  0.138385  0.169825  0.505144
1  0.222367  0.879290  0.872116  0.884503  0.323610
2  0.570911  0.158771  0.180097  0.185030  0.039071
3  0.228102  0.630493  0.161913  0.422415  0.307673
4  0.657030  0.868799  0.950075  0.557719  0.343548

In [373]:
df2=df2[df>0.4]
df2

          0         1         2         3         4
0  0.942650  0.382884  0.138385       NaN  0.505144
1  0.222367  0.879290  0.872116  0.884503       NaN
2       NaN  0.158771  0.180097  0.185030  0.039071
3  0.228102       NaN  0.161913  0.422415       NaN
4  0.657030  0.868799  0.950075  0.557719  0.343548

In [372]:
df2=df2.fillna(value=0)
df2

          0         1         2         3         4
0  0.942650  0.382884  0.138385  0.000000  0.505144
1  0.222367  0.879290  0.872116  0.884503  0.000000
2  0.000000  0.158771  0.180097  0.185030  0.039071
3  0.228102  0.000000  0.161913  0.422415  0.000000
4  0.657030  0.868799  0.950075  0.557719  0.343548

In [374]:
df2.fillna({
    0 : ((df2[0].median())+(df2[0].mean()))/2,
    1 : df2[1].median(), 
    2 : df2[2].median(),
    3 : df2[3].median(),
    4 : df2[4].median(),
},inplace=True)
df2

          0         1         2         3         4
0  0.942650  0.382884  0.138385  0.490067  0.505144
1  0.222367  0.879290  0.872116  0.884503  0.343548
2  0.477552  0.158771  0.180097  0.185030  0.039071
3  0.228102  0.625842  0.161913  0.422415  0.343548
4  0.657030  0.868799  0.950075  0.557719  0.343548

In [376]:
import pandas as pd

data = {
    'Store Name': ['Pizza Hut', 'PizzaBurg', 'Dominos', 'Pizza Hut', 'Dominos', 'Pizza Hut', 'PizzaRella'],
    'Location': ['Dhanmondi', 'Taltola', 'Dhanmondi', 'Mirpur', 'Mirpur', 'Gulshan', 'taltola'],
    'Price': [651, 311, 637, 626, 363, 387, 375]
}

dff = pd.DataFrame(data)

# Display the DataFrame
dff

   Store Name   Location  Price
0   Pizza Hut  Dhanmondi    651
1   PizzaBurg    Taltola    311
2     Dominos  Dhanmondi    637
3   Pizza Hut     Mirpur    626
4     Dominos     Mirpur    363
5   Pizza Hut    Gulshan    387
6  PizzaRella    taltola    375

In [380]:
dff.groupby('Store Name').max()

           Location  Price
Store Name
Dominos      Mirpur    637
Pizza Hut    Mirpur    651
PizzaBurg   Taltola    311
PizzaRella  taltola    375

In [384]:
dff.groupby('Store Name')['Price'].max()

Store Name
Dominos       637
Pizza Hut     651
PizzaBurg     311
PizzaRella    375
Name: Price, dtype: int64

In [386]:
dff.groupby('Store Name').mean(numeric_only=True)

                 Price
Store Name
Dominos     500.000000
Pizza Hut   554.666667
PizzaBurg   311.000000
PizzaRella  375.000000

In [391]:
left = pd.DataFrame({
    'key1': ['K0', 'K1', 'K2', 'K3'],
    'A': np.random.randint(1, 10, size=4),
    'B': np.random.randint(1, 10, size=4)
})
right=pd.DataFrame(
    data={
        'key1' : ['K0', 'K2', 'K4', 'K5'], 
        'A' : np.random.randint(10,20,4), 
        'B' : np.random.randint(20,40,4)
    }
    
)

In [392]:
left

  key1  A  B
0   K0  1  6
1   K1  4  4
2   K2  3  7
3   K3  4  4

In [393]:
right

  key1   A   B
0   K0  12  37
1   K2  19  21
2   K4  11  23
3   K5  13  31

In [394]:
pd.merge(left,right,on='key1',how='inner')

  key1  A_x  B_x  A_y  B_y
0   K0    1    6   12   37
1   K2    3    7   19   21

In [395]:
pd.merge(left,right,on='key1',how='outer')

  key1  A_x  B_x   A_y   B_y
0   K0  1.0  6.0  12.0  37.0
1   K1  4.0  4.0   NaN   NaN
2   K2  3.0  7.0  19.0  21.0
3   K3  4.0  4.0   NaN   NaN
4   K4  NaN  NaN  11.0  23.0
5   K5  NaN  NaN  13.0  31.0

In [396]:
pd.merge(left,right,on='key1',how='left')

  key1  A_x  B_x   A_y   B_y
0   K0    1    6  12.0  37.0
1   K1    4    4   NaN   NaN
2   K2    3    7  19.0  21.0
3   K3    4    4   NaN   NaN

In [421]:
left = pd.DataFrame(
    index=[1,2,3,4],
    data={
    
    'A': np.random.randint(1, 10, size=4),
    'B': np.random.randint(1, 10, size=4)
})
right=pd.DataFrame(
    index=[3,4,5,6],
    data={
        'C' : np.random.randint(10,20,4), 
        'D' : np.random.randint(20,40,4)
    }
    
)

In [422]:
left

   A  B
1  4  3
2  4  2
3  1  9
4  3  5

In [423]:
right

    C   D
3  10  22
4  17  35
5  12  24
6  18  37

In [425]:
left.join(right,how='inner')

   A  B   C   D
3  1  9  10  22
4  3  5  17  35

In [427]:
data = {
    'col1': np.random.randint(1, 10, 50),
    'col2': np.random.randint(100, 500, 50),
    'col3' : np.random.choice(['Jack','Nora','Katrina','Sara','Sabrina'],50)
}

df = pd.DataFrame(data)

In [428]:
df.head(7)

   col1  col2     col3
0     6   452     Nora
1     5   347     Sara
2     1   192     Nora
3     9   418     Jack
4     5   260     Nora
5     9   347     Jack
6     7   106  Katrina

In [429]:
df['col3'].unique()

array(['Nora', 'Sara', 'Jack', 'Katrina', 'Sabrina'], dtype=object)

In [430]:
df['col3'].value_counts()

col3
Sara       12
Nora       11
Sabrina    11
Katrina     9
Jack        7
Name: count, dtype: int64

In [431]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    50 non-null     int64
 1   col2    50 non-null     int64
 2   col3    50 non-null     object
dtypes: int64(2), object(1)
memory usage: 1.3+ KB

In [433]:
df.describe()

            col1       col2
count  50.000000   50.00000
mean    5.100000  311.88000
std     2.358225  104.12505
min     1.000000  106.00000
25%     4.000000  227.25000
50%     5.000000  328.00000
75%     7.000000  390.75000
max     9.000000  482.00000

In [448]:
dfs=df.sort_values(by='col2')
dfs=dfs.reset_index(drop=True)
dfs.head()

   col1  col2     col3
0     7   106  Katrina
1     8   111     Sara
2     4   128     Nora
3     4   137  Katrina
4     2   137     Sara

In [449]:
def times(x) : 
    return "victim : " + x ;

In [450]:
dfs['col3']=dfs['col3'].apply(times)
dfs.head()

   col1  col2              col3
0     7   106  victim : Katrina
1     8   111     victim : Sara
2     4   128     victim : Nora
3     4   137  victim : Katrina
4     2   137     victim : Sara

In [452]:
df.to_csv('testing.csv')

In [456]:
dff=pd.read_csv('testing.csv',index_col=0)
dff.head(7)

   col1  col2     col3
0     6   452     Nora
1     5   347     Sara
2     1   192     Nora
3     9   418     Jack
4     5   260     Nora
5     9   347     Jack
6     7   106  Katrina