In [23]:
import numpy as np 
import pandas as pd

In [24]:
data=np.arange(6,11)
data

array([ 6,  7,  8,  9, 10])

In [27]:
pd_series1=pd.Series(data=data)
pd_series1
print('2nd index : ')
pd_series1[1]

2nd index :

np.int64(7)

In [28]:
indx=np.array([chr(i) for i in range(ord('a'),ord('f'))])
indx

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [29]:
pd_series1.index=indx
pd_series1

a     6
b     7
c     8
d     9
e    10
dtype: int64

In [30]:
print('2nd index : ')
pd_series1['b']

2nd index :

np.int64(7)

In [31]:
pd_series2=pd.Series(data=data*2 ,index=indx) 
pd_series2

a    12
b    14
c    16
d    18
e    20
dtype: int64

In [33]:
dic={
    'a' : 'Tamzid', 
    'b' : 'Ronaldo', 
    'c' : 'Totty'
}
pd_series3=pd.Series(data=dic) 
pd_series3
print('2nd index : ') 
pd_series3['b']

2nd index :

'Ronaldo'

In [37]:
#2

In [64]:
data= np.random.rand(6,5) 
data

array([[0.45526868, 0.85350088, 0.92339834, 0.12250198, 0.59331832],
       [0.82497669, 0.60535015, 0.97030546, 0.74987776, 0.38369415],
       [0.45403349, 0.07453928, 0.27158117, 0.2848892 , 0.75266815],
       [0.94763731, 0.17865022, 0.82727429, 0.8814587 , 0.91811633],
       [0.06407082, 0.07145504, 0.33043346, 0.08150768, 0.66891805],
       [0.34885089, 0.66140309, 0.79159497, 0.31436398, 0.80082223]])

In [65]:
df=pd.DataFrame(data) 
df

          0         1         2         3         4
0  0.455269  0.853501  0.923398  0.122502  0.593318
1  0.824977  0.605350  0.970305  0.749878  0.383694
2  0.454033  0.074539  0.271581  0.284889  0.752668
3  0.947637  0.178650  0.827274  0.881459  0.918116
4  0.064071  0.071455  0.330433  0.081508  0.668918
5  0.348851  0.661403  0.791595  0.314364  0.800822

In [66]:
df.loc[:,[0,1,2]]

          0         1         2
0  0.455269  0.853501  0.923398
1  0.824977  0.605350  0.970305
2  0.454033  0.074539  0.271581
3  0.947637  0.178650  0.827274
4  0.064071  0.071455  0.330433
5  0.348851  0.661403  0.791595

In [67]:
df.loc[[0,1,2]]

          0         1         2         3         4
0  0.455269  0.853501  0.923398  0.122502  0.593318
1  0.824977  0.605350  0.970305  0.749878  0.383694
2  0.454033  0.074539  0.271581  0.284889  0.752668

In [68]:
df.loc[[1,2],[0,1,2]]

          0         1         2
1  0.824977  0.605350  0.970305
2  0.454033  0.074539  0.271581

In [69]:
df.loc[3,1]

np.float64(0.1786502162505853)

In [70]:
df[0]

0    0.455269
1    0.824977
2    0.454033
3    0.947637
4    0.064071
5    0.348851
Name: 0, dtype: float64

In [71]:
type(df[0]) #every column is a series

pandas.core.series.Series

In [72]:
df.loc[0,:]

0    0.455269
1    0.853501
2    0.923398
3    0.122502
4    0.593318
Name: 0, dtype: float64

In [73]:
type(df.iloc[0,:]) # every rows are series as well

pandas.core.series.Series

In [82]:
row=['r1','r2','r3','r4','r5','r5']
col=['c1','c2','c3','c4','c5']
df2=pd.DataFrame(data=data,index=row,columns=col) 
df2

          c1        c2        c3        c4        c5
r1  0.455269  0.853501  0.923398  0.122502  0.593318
r2  0.824977  0.605350  0.970305  0.749878  0.383694
r3  0.454033  0.074539  0.271581  0.284889  0.752668
r4  0.947637  0.178650  0.827274  0.881459  0.918116
r5  0.762807  0.547632  0.761913  0.684537  0.956747
r5  0.762807  0.547632  0.761913  0.684537  0.956747

In [83]:
df2.loc[:,['c2','c3','c4']]

          c2        c3        c4
r1  0.853501  0.923398  0.122502
r2  0.605350  0.970305  0.749878
r3  0.074539  0.271581  0.284889
r4  0.178650  0.827274  0.881459
r5  0.547632  0.761913  0.684537
r5  0.547632  0.761913  0.684537

In [84]:
df2.iloc[:,[1,2,3]]

          c2        c3        c4
r1  0.853501  0.923398  0.122502
r2  0.605350  0.970305  0.749878
r3  0.074539  0.271581  0.284889
r4  0.178650  0.827274  0.881459
r5  0.547632  0.761913  0.684537
r5  0.547632  0.761913  0.684537

In [85]:
df2['new']=np.random.rand(6) 
df2

          c1        c2        c3        c4        c5       new
r1  0.455269  0.853501  0.923398  0.122502  0.593318  0.679693
r2  0.824977  0.605350  0.970305  0.749878  0.383694  0.859798
r3  0.454033  0.074539  0.271581  0.284889  0.752668  0.757422
r4  0.947637  0.178650  0.827274  0.881459  0.918116  0.198679
r5  0.762807  0.547632  0.761913  0.684537  0.956747  0.543388
r5  0.762807  0.547632  0.761913  0.684537  0.956747  0.527994

In [86]:
df2.loc['r6',:]=np.random.rand(6) 
df2

          c1        c2        c3        c4        c5       new
r1  0.455269  0.853501  0.923398  0.122502  0.593318  0.679693
r2  0.824977  0.605350  0.970305  0.749878  0.383694  0.859798
r3  0.454033  0.074539  0.271581  0.284889  0.752668  0.757422
r4  0.947637  0.178650  0.827274  0.881459  0.918116  0.198679
r5  0.762807  0.547632  0.761913  0.684537  0.956747  0.543388
r5  0.762807  0.547632  0.761913  0.684537  0.956747  0.527994
r6  0.435119  0.936733  0.630275  0.681375  0.682845  0.480933

In [88]:
row=['r1','r2','r3']
col=['c1','c2']
data=np.random.rand(3,2)
df3=pd.DataFrame(data=data,index=row,columns=col) 
df3

          c1        c2
r1  0.929057  0.391614
r2  0.136407  0.904320
r3  0.449479  0.389204

In [96]:
dic={
    'r1' : [1,2,3,3,5], 
    'r2' : [9,8,7,6,5]
}
df4=pd.DataFrame(data=dic) 
df4

   r1  r2
0   1   9
1   2   8
2   3   7
3   3   6
4   5   5

In [97]:
#but its taking dic input as a column so we will transpose it 
df4=df4.T
df4

    0  1  2  3  4
r1  1  2  3  3  5
r2  9  8  7  6  5