In [89]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn import linear_model as lnr

In [90]:
df=pd.read_excel('home_prices.xlsx',index_col=0)
df.head()

   area  bedrooms  age   price
0  2689       2.0   22  420000
1  2966       2.0   28  422000
2  3269       2.0    2  573000
3  3275       2.0    6  516000
4  3360       3.0   28  536000

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   area      50 non-null     int64
 1   bedrooms  49 non-null     float64
 2   age       50 non-null     int64
 3   price     50 non-null     int64
dtypes: float64(1), int64(3)
memory usage: 2.0 KB

In [92]:
dff=df[['area','bedrooms']]
dff=dff.dropna()

In [93]:
regt=lnr.LinearRegression()
regt.fit(dff[['area']],dff.bedrooms)

LinearRegression()

In [94]:
df['bedrooms'] = df['bedrooms'].fillna(pd.Series(regt.predict(df[['area']])))

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   area      50 non-null     int64
 1   bedrooms  50 non-null     float64
 2   age       50 non-null     int64
 3   price     50 non-null     int64
dtypes: float64(1), int64(3)
memory usage: 2.0 KB

In [96]:
#Multi dimantion linear reg

In [97]:
reg=lnr.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [98]:
reg.predict([[3333,4,7]]).astype(int)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([606268])

In [99]:
df['predicted_prices'] = reg.predict(df[['area', 'bedrooms', 'age']]).astype(int)

In [100]:
df.head()

   area  bedrooms  age   price  predicted_prices
0  2689       2.0   22  420000            437620
1  2966       2.0   28  422000            456923
2  3269       2.0    2  573000            550553
3  3275       2.0    6  516000            542353
4  3360       3.0   28  536000            533035

In [101]:
df['error']=(((df['price']-df['predicted_prices'])/df['price'])*100).astype(int).astype(str)+"%"

In [102]:
df.head()

   area  bedrooms  age   price  predicted_prices error
0  2689       2.0   22  420000            437620   -4%
1  2966       2.0   28  422000            456923   -8%
2  3269       2.0    2  573000            550553    3%
3  3275       2.0    6  516000            542353   -5%
4  3360       3.0   28  536000            533035    0%

In [103]:
df.to_csv('home_prices_predicted.csv', index=False)